[package]
name = "axis"
version = "0.1.0"
authors = ["Jeremy Zheng <jitang.zheng@gmail.com>"]
description = "A web application by Rust and React.."
homepage = "https://github.com/saturn-xiv/arete"
license = "MIT"

[profile.release]
lto = true

[dependencies]
log = "0.4"
log4rs = "0.8"
toml = "0.4"
failure = "0.1"
zmq = "0.9"
nix = "0.13"
mustache = "*"
serde = "1"
serde_derive = "1"
serde_json = "1"
clap = "2"

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.diesel]
version = "1"
features = ["sqlite", "chrono"]

[package.metadata.deb]
depends = "$auto, systemd"
section = "admin"
priority = "optional"
assets = [
    ["assets/agent.service", "/usr/lib/systemd/system/axis-agent", "644"],
    ["assets/master.service", "/usr/lib/systemd/system/axis-master", "644"],
    ["assets/agent.yml", "etc/axis/", "600"],
    ["assets/master.yml", "etc/axis/", "600"],
    ["assets/log4rs.yml", "etc/axis/", "644"],    
    ["target/release/axis", "usr/bin/", "755"]
]